### ISSUE TITLE
Export libmarisa from Google Code to GitHub

### ISSUE THREAD

**Issue by hickford** [s-yata/marisa2#1]
Hi Susumu. [Google Code is shutting down](http://google-opensource.blogspot.co.uk/2015/03/farewell-to-google-code.html). Would you consider copying your libmarisa project to GitHub?

> READ-ONLY: This project has been archived. For more information see [this post](https://code.google.com/p/support/wiki/ReadOnlyTransition).

https://code.google.com/p/marisa-trie/

**Comment by pombredanne** [comment]
:+1:

**Comment by s-yata** [comment]
:ok_hand:

**Comment by s-yata** [comment]
Done.
https://github.com/s-yata/marisa-trie

**Comment by pombredanne** [comment]
@s-yata Thank you!
